# Generated by Django 3.2.4 on 2021-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'Уроки', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='lessons',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
