# Generated by Django 3.2.4 on 2021-09-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20210910_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donelessonsmodel',
            options={'verbose_name': 'Пройденные уроки', 'verbose_name_plural': 'Пройденные уроки'},
        ),
        migrations.AlterField(
            model_name='donelessonsmodel',
            name='lessons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='lessons.lessons'),
        ),
    ]
