# Generated by Django 3.2.4 on 2021-12-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20210911_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='answer5',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant11',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant12',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant13',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant14',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant15',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant21',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant22',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant23',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant24',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant25',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant31',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant32',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant33',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant34',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant35',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant41',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant42',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant43',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant44',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='variant45',
        ),
        migrations.CreateModel(
            name='PracticeTest',
            fields=[
                ('questionid', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('variant1', models.CharField(max_length=255)),
                ('variant2', models.CharField(max_length=255)),
                ('variant3', models.CharField(max_length=255)),
                ('variant4', models.CharField(max_length=255)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lessons')),
            ],
            options={
                'verbose_name': 'Тесты',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
