# Generated by Django 3.2.4 on 2021-12-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20211218_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetest',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedtest', to='lessons.lessons'),
        ),
    ]
