# Generated by Django 3.2.4 on 2021-12-18 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_practicetest_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetest',
            name='questionid',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
