# Generated by Django 3.2.4 on 2021-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_practicetest_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donelessonsmodel',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
