# Generated by Django 3.2.4 on 2021-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_donelessonsmodel_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donelessonsmodel',
            name='mark',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
