# Generated by Django 3.2.4 on 2021-12-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_donelessonsmodel_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donelessonsmodel',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
